// SPDX-FileCopyrightText: 2025 NOI Techpark <digital@noi.bz.it>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ViewLayout } from "./utils/breakpoints";
import { Map } from "leaflet";
import { IconName } from "./blocks/icon/icon.component";
export { ViewLayout } from "./utils/breakpoints";
export { Map } from "leaflet";
export { IconName } from "./blocks/icon/icon.component";
export namespace Components {
    /**
     * Road traffic events component
     */
    interface NoiA22RoadEvents {
        /**
          * Events direction filter
          * @default 'both'
         */
        "direction": 'north' | 'south' | 'both';
        /**
          * Language
          * @default 'it'
         */
        "language": string;
        /**
          * Layout appearance
          * @default 'auto'
         */
        "layout": ViewLayout;
        /**
          * Reload camera data (basically, it's images)
         */
        "refreshData": () => Promise<void>;
    }
    /**
     * (INTERNAL) render leaflet map
     */
    interface NoiBrennerlecMap {
    }
    /**
     * (INTERNAL) Backdrop component.
     */
    interface NoiButton {
        /**
          * button 'disabled' property
          * @default false
         */
        "disabled": boolean;
        /**
          * icon-only buttons has circle shape. The size of the button can be changed with "font-size" style
          * @default false
         */
        "iconOnly": boolean;
    }
    /**
     * (INTERNAL) render an icon.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface NoiIcon {
        /**
          * icon name
         */
        "name": IconName | string;
        /**
          * icon url
         */
        "src"?: string;
    }
}
export interface NoiBrennerlecMapCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiBrennerlecMapElement;
}
export interface NoiButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNoiButtonElement;
}
declare global {
    /**
     * Road traffic events component
     */
    interface HTMLNoiA22RoadEventsElement extends Components.NoiA22RoadEvents, HTMLStencilElement {
    }
    var HTMLNoiA22RoadEventsElement: {
        prototype: HTMLNoiA22RoadEventsElement;
        new (): HTMLNoiA22RoadEventsElement;
    };
    interface HTMLNoiBrennerlecMapElementEventMap {
        "mapReady": Map;
    }
    /**
     * (INTERNAL) render leaflet map
     */
    interface HTMLNoiBrennerlecMapElement extends Components.NoiBrennerlecMap, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiBrennerlecMapElementEventMap>(type: K, listener: (this: HTMLNoiBrennerlecMapElement, ev: NoiBrennerlecMapCustomEvent<HTMLNoiBrennerlecMapElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiBrennerlecMapElementEventMap>(type: K, listener: (this: HTMLNoiBrennerlecMapElement, ev: NoiBrennerlecMapCustomEvent<HTMLNoiBrennerlecMapElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiBrennerlecMapElement: {
        prototype: HTMLNoiBrennerlecMapElement;
        new (): HTMLNoiBrennerlecMapElement;
    };
    interface HTMLNoiButtonElementEventMap {
        "btnClick": MouseEvent;
    }
    /**
     * (INTERNAL) Backdrop component.
     */
    interface HTMLNoiButtonElement extends Components.NoiButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNoiButtonElementEventMap>(type: K, listener: (this: HTMLNoiButtonElement, ev: NoiButtonCustomEvent<HTMLNoiButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNoiButtonElementEventMap>(type: K, listener: (this: HTMLNoiButtonElement, ev: NoiButtonCustomEvent<HTMLNoiButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNoiButtonElement: {
        prototype: HTMLNoiButtonElement;
        new (): HTMLNoiButtonElement;
    };
    /**
     * (INTERNAL) render an icon.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface HTMLNoiIconElement extends Components.NoiIcon, HTMLStencilElement {
    }
    var HTMLNoiIconElement: {
        prototype: HTMLNoiIconElement;
        new (): HTMLNoiIconElement;
    };
    interface HTMLElementTagNameMap {
        "noi-a22-road-events": HTMLNoiA22RoadEventsElement;
        "noi-brennerlec-map": HTMLNoiBrennerlecMapElement;
        "noi-button": HTMLNoiButtonElement;
        "noi-icon": HTMLNoiIconElement;
    }
}
declare namespace LocalJSX {
    /**
     * Road traffic events component
     */
    interface NoiA22RoadEvents {
        /**
          * Events direction filter
          * @default 'both'
         */
        "direction"?: 'north' | 'south' | 'both';
        /**
          * Language
          * @default 'it'
         */
        "language"?: string;
        /**
          * Layout appearance
          * @default 'auto'
         */
        "layout"?: ViewLayout;
    }
    /**
     * (INTERNAL) render leaflet map
     */
    interface NoiBrennerlecMap {
        /**
          * Emitted when map is initialized and ready to draw on it
         */
        "onMapReady"?: (event: NoiBrennerlecMapCustomEvent<Map>) => void;
    }
    /**
     * (INTERNAL) Backdrop component.
     */
    interface NoiButton {
        /**
          * button 'disabled' property
          * @default false
         */
        "disabled"?: boolean;
        /**
          * icon-only buttons has circle shape. The size of the button can be changed with "font-size" style
          * @default false
         */
        "iconOnly"?: boolean;
        /**
          * Emitted when user clicks on the button
         */
        "onBtnClick"?: (event: NoiButtonCustomEvent<MouseEvent>) => void;
    }
    /**
     * (INTERNAL) render an icon.
     * Icons are embedded inside the component (so far).
     * Icon size can be changed by 'font-size' style
     */
    interface NoiIcon {
        /**
          * icon name
         */
        "name"?: IconName | string;
        /**
          * icon url
         */
        "src"?: string;
    }

    interface NoiA22RoadEventsAttributes {
        "language": string;
        "layout": ViewLayout;
        "direction": 'north' | 'south' | 'both';
    }
    interface NoiButtonAttributes {
        "disabled": boolean;
        "iconOnly": boolean;
    }
    interface NoiIconAttributes {
        "name": IconName | string;
        "src": string;
    }

    interface IntrinsicElements {
        "noi-a22-road-events": Omit<NoiA22RoadEvents, keyof NoiA22RoadEventsAttributes> & { [K in keyof NoiA22RoadEvents & keyof NoiA22RoadEventsAttributes]?: NoiA22RoadEvents[K] } & { [K in keyof NoiA22RoadEvents & keyof NoiA22RoadEventsAttributes as `attr:${K}`]?: NoiA22RoadEventsAttributes[K] } & { [K in keyof NoiA22RoadEvents & keyof NoiA22RoadEventsAttributes as `prop:${K}`]?: NoiA22RoadEvents[K] };
        "noi-brennerlec-map": NoiBrennerlecMap;
        "noi-button": Omit<NoiButton, keyof NoiButtonAttributes> & { [K in keyof NoiButton & keyof NoiButtonAttributes]?: NoiButton[K] } & { [K in keyof NoiButton & keyof NoiButtonAttributes as `attr:${K}`]?: NoiButtonAttributes[K] } & { [K in keyof NoiButton & keyof NoiButtonAttributes as `prop:${K}`]?: NoiButton[K] };
        "noi-icon": Omit<NoiIcon, keyof NoiIconAttributes> & { [K in keyof NoiIcon & keyof NoiIconAttributes]?: NoiIcon[K] } & { [K in keyof NoiIcon & keyof NoiIconAttributes as `attr:${K}`]?: NoiIconAttributes[K] } & { [K in keyof NoiIcon & keyof NoiIconAttributes as `prop:${K}`]?: NoiIcon[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Road traffic events component
             */
            "noi-a22-road-events": LocalJSX.IntrinsicElements["noi-a22-road-events"] & JSXBase.HTMLAttributes<HTMLNoiA22RoadEventsElement>;
            /**
             * (INTERNAL) render leaflet map
             */
            "noi-brennerlec-map": LocalJSX.IntrinsicElements["noi-brennerlec-map"] & JSXBase.HTMLAttributes<HTMLNoiBrennerlecMapElement>;
            /**
             * (INTERNAL) Backdrop component.
             */
            "noi-button": LocalJSX.IntrinsicElements["noi-button"] & JSXBase.HTMLAttributes<HTMLNoiButtonElement>;
            /**
             * (INTERNAL) render an icon.
             * Icons are embedded inside the component (so far).
             * Icon size can be changed by 'font-size' style
             */
            "noi-icon": LocalJSX.IntrinsicElements["noi-icon"] & JSXBase.HTMLAttributes<HTMLNoiIconElement>;
        }
    }
}
